set(_CATKIN_CURRENT_PACKAGE "tzc_transport")
set(tzc_transport_VERSION "0.0.0")
set(tzc_transport_MAINTAINER "Jrdevil-Wang <stu_981523@163.com>")
set(tzc_transport_PACKAGE_FORMAT "1")
set(tzc_transport_BUILD_DEPENDS "roscpp")
set(tzc_transport_BUILD_EXPORT_DEPENDS "roscpp")
set(tzc_transport_BUILDTOOL_DEPENDS "catkin")
set(tzc_transport_BUILDTOOL_EXPORT_DEPENDS )
set(tzc_transport_EXEC_DEPENDS "roscpp")
set(tzc_transport_RUN_DEPENDS "roscpp")
set(tzc_transport_TEST_DEPENDS )
set(tzc_transport_DOC_DEPENDS )
set(tzc_transport_DEPRECATED "")